name: form_helper
description: Flutter plugin to help you validate forms.
version: 0.0.1
homepage: https://github.com/dartclub/form_helper

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
